name: Create Release
on:
    push:
      tags:
        - 'v*'

jobs:
    create_release:
      name: Create Release ${{ github.ref_name }}
      runs-on: ubuntu-latest
      steps:
        - run: echo "hello world"
          
  
    