name: Release Workflow

on:
  push:
    branches:
      - "feature/*"
permissions:
     contents: write
     pull-requests: write
jobs:
  release-job:
    runs-on: ubuntu-latest
    ############################################
    # Grant status permission for MULTI_STATUS #
    ############################################
    permissions:
      contents: read
      packages: read
      statuses: write

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0
      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: super-linter/super-linter/slim@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JAVASCRIPT_ES: true	
          DEFAULT_BRANCH: 'feature/*'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  