name: Release Workflow

on:
  push:
    branches:
      - 'main'
permissions:
     contents: write
     pull-requests: write
jobs:
  release-job:
    runs-on: ubuntu-latest

    steps:
      - run: echo ${{github.event.pull_request.state}}  
      - run: echo ${{github.event.pull_request.merged}}  

      - name: Check out code
        uses: actions/checkout@v2

      - name: Release with release-please
        uses: google-github-actions/release-please-action@v3.7.12
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node

      - name: Release with release-please
        uses: google-github-actions/release-please-action@v3.7.12
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          default-branch: develop  
  